# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    pedidos.service:
        class: AppBundle\Service\PedidosService
        arguments: ["@doctrine.orm.entity_manager"]
    chamado.service:
        class: AppBundle\Service\ChamadoService
        arguments: ["@doctrine.orm.entity_manager"]

    clientes.service:
        class: AppBundle\Service\ClientesService
        arguments: ["@doctrine.orm.entity_manager"]